version: '3.8'

services:
  api:
    container_name: bpn_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5138:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: bpn_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
